In [2]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Desktop\Capgemini Training\Capgemini Sprint Evaluation\Pollution_Control--CG\dataset\pollution.csv")

In [3]:
df.head()

,Record_ID,Plant_ID,TS,PM2.5,SO2,NOx,Unit,"Lat,Lon",Status
0,E20000,PL-08,2026-01-01 00:00+05:30,73.1,18.7,25.4,ug/m³,"13.2214,81.4807",Ok
1,E20001,PL-01,2026-01-01 00:10,73.1,26.2,49.9,ug/m3,"12.6208,79.5575",ok
2,E20002,PL-10,2026-01-01 00:20,83.0,26.1,45.5,UG/m3,"12.727,81.2451",MAINTENANCE
3,E20003,PL-17,2026-01-01 00:30,64.5,31.0,49.9,ug/m3,"13.5187,81.0188",Maint
4,E20004,PL-11,2026-01-01 00:40,82.1,22.0,51.9,µg/m³,"13.2038,80.0315",OK

In [4]:
df.tail()

,Record_ID,Plant_ID,TS,PM2.5,SO2,NOx,Unit,"Lat,Lon",Status
6625,E22690,PL-01,2026-01-19 16:20,5.7,22.8,24.7,mg/nm3,"12.6203,79.9658",FAULT
6626,E26085,PL-14,2026-02-12 06:10,129.6,35.8,80.4,UG/m3,"13.4076,80.4396",maintenance
6627,E20397,PL-02,2026-01-03 18:10,11.0,NaN,11.0,UG/m3,"13.6809,79.516",ok
6628,E24722,PL-02,2026-02-02 19:00,17.1,9.0,24.2,mg/Nm3,"14.4605,80.7726",Maint
6629,E21263,PL-20,2026-01-09 18:30,27.4,NaN,31.5,mg/nm3,"13.7189,81.1412",OK

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6630 entries, 0 to 6629
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Record_ID  6630 non-null   str
 1   Plant_ID   6630 non-null   str
 2   TS         6630 non-null   str
 3   PM2.5      6549 non-null   float64
 4   SO2        6286 non-null   float64
 5   NOx        6433 non-null   float64
 6   Unit       6630 non-null   str
 7   Lat,Lon    6559 non-null   str
 8   Status     6612 non-null   str
dtypes: float64(3), str(6)
memory usage: 466.3 KB

In [6]:
df.describe()

              PM2.5           SO2           NOx
count   6549.000000   6286.000000   6433.000000
mean     141.319386    127.904637    152.930365
std     1457.528654   1751.110746   1902.598084
min    -1041.500000    -49.830000  -1276.000000
25%       36.400000     18.300000     28.100000
50%       66.900000     25.200000     48.600000
75%       99.100000     32.000000     69.700000
max    41504.200000  48937.700000  49329.000000

In [7]:
demo = df
demo.columns = df.columns.str.strip()
demo.head()

,Record_ID,Plant_ID,TS,PM2.5,SO2,NOx,Unit,"Lat,Lon",Status
0,E20000,PL-08,2026-01-01 00:00+05:30,73.1,18.7,25.4,ug/m³,"13.2214,81.4807",Ok
1,E20001,PL-01,2026-01-01 00:10,73.1,26.2,49.9,ug/m3,"12.6208,79.5575",ok
2,E20002,PL-10,2026-01-01 00:20,83.0,26.1,45.5,UG/m3,"12.727,81.2451",MAINTENANCE
3,E20003,PL-17,2026-01-01 00:30,64.5,31.0,49.9,ug/m3,"13.5187,81.0188",Maint
4,E20004,PL-11,2026-01-01 00:40,82.1,22.0,51.9,µg/m³,"13.2038,80.0315",OK

---------- 1. Datetime normalization (24:10 → next day 00:10) ----------

In [8]:
def fix_datetime(ts):
    ts = str(ts)

    date_part = ts.split()[0]
    time_part = ts.split()[1]
    time_part = time_part.split("+")[0]

    hour = int(time_part.split(":")[0])
    minute = int(time_part.split(":")[1])

    date = pd.to_datetime(date_part, dayfirst=True)

    extra_days = hour // 24
    new_hour = hour % 24

    date = date + pd.Timedelta(days=extra_days)

    return pd.to_datetime(f"{date.date()} {new_hour:02d}:{minute:02d}")

demo["TS"] = demo["TS"].apply(fix_datetime)
demo.head()

C:\Users\KIIT\AppData\Local\Temp\ipykernel_18180\1189334576.py:11: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  date = pd.to_datetime(date_part, dayfirst=True)

,Record_ID,Plant_ID,TS,PM2.5,SO2,NOx,Unit,"Lat,Lon",Status
0,E20000,PL-08,2026-01-01 00:00:00,73.1,18.7,25.4,ug/m³,"13.2214,81.4807",Ok
1,E20001,PL-01,2026-01-01 00:10:00,73.1,26.2,49.9,ug/m3,"12.6208,79.5575",ok
2,E20002,PL-10,2026-01-01 00:20:00,83.0,26.1,45.5,UG/m3,"12.727,81.2451",MAINTENANCE
3,E20003,PL-17,2026-01-01 00:30:00,64.5,31.0,49.9,ug/m3,"13.5187,81.0188",Maint
4,E20004,PL-11,2026-01-01 00:40:00,82.1,22.0,51.9,µg/m³,"13.2038,80.0315",OK

---------- 2. Unit standardization (ug/m3, µg/m³ → ug/m3) ----------

In [9]:
demo["Unit"] = (demo["Unit"].astype(str).str.strip().str.lower().replace({
        "ug/m³": "ug/m3",
        "µg/m³": "ug/m3",
        "ug/m3": "ug/m3",
        "ug/m3 ": "ug/m3",
        "mg/nm3": "mg/nm3",
        "mg/nm³": "mg/nm3"})
)

demo["Unit"].unique()

<StringArray>
['ug/m3', 'mg/nm3']
Length: 2, dtype: str

---------- 3. Whitespace trimming and casing standardization for status ----------

In [10]:
demo["Status"] = (demo["Status"].astype(str).str.strip().str.upper())
demo["Status"] = demo["Status"].fillna("unknown")
demo["Status"] = (demo["Status"].astype(str).str.strip().str.lower().replace({
        "maint": "maintenance",
        "maintenance": "maintenance",
        "err": "fault",
        "fault": "fault",
        "--": "unknown",
        "0": "unknown",
        "?": "unknown",
        "nan": "unknown"})
)

demo["Status"].unique()

<StringArray>
['ok', 'maintenance', 'fault', 'unknown']
Length: 4, dtype: str

---------- 4. Coordinate parsing and range validation ----------

In [11]:
demo[["Latitude", "Longitude"]] = demo["Lat,Lon"].str.split(",", expand=True)

demo["Latitude"] = pd.to_numeric(demo["Latitude"], errors="coerce")
demo["Longitude"] = pd.to_numeric(demo["Longitude"], errors="coerce")

demo.loc[(demo["Latitude"] < -90) | (demo["Latitude"] > 90), "Latitude"] = None
demo.loc[(demo["Longitude"] < -180) | (demo["Longitude"] > 180), "Longitude"] = None

demo = demo.drop(columns=["Lat,Lon"])
demo[["Latitude", "Longitude"]].head()

   Latitude  Longitude
0   13.2214    81.4807
1   12.6208    79.5575
2   12.7270    81.2451
3   13.5187    81.0188
4   13.2038    80.0315

---------- 5. Negative and impossible concentration checks ----------

In [12]:
demo["PM2.5"] = pd.to_numeric(demo["PM2.5"], errors="coerce")
demo["SO2"] = pd.to_numeric(demo["SO2"], errors="coerce")
demo["NOx"] = pd.to_numeric(demo["NOx"], errors="coerce")

demo.loc[demo["PM2.5"] < 0, "PM2.5"] = None
demo.loc[demo["SO2"] < 0, "SO2"] = None
demo.loc[demo["NOx"] < 0, "NOx"] = None

demo.loc[demo["PM2.5"] > 1000, "PM2.5"] = None
demo.loc[demo["SO2"] > 2000, "SO2"] = None
demo.loc[demo["NOx"] > 2000, "NOx"] = None

demo[["PM2.5", "SO2", "NOx"]].head()

   PM2.5   SO2   NOx
0   73.1  18.7  25.4
1   73.1  26.2  49.9
2   83.0  26.1  45.5
3   64.5  31.0  49.9
4   82.1  22.0  51.9

---------- 6. Duplicate merge by (Plant_ID, TS) ----------

In [13]:
demo[demo.duplicated(subset=["Plant_ID", "TS"], keep=False)]

demo["PM2.5"] = demo.groupby(["Plant_ID", "TS"])["PM2.5"].transform("mean")
demo["SO2"] = demo.groupby(["Plant_ID", "TS"])["SO2"].transform("mean")
demo["NOx"] = demo.groupby(["Plant_ID", "TS"])["NOx"].transform("mean")

---------- 7. Sensor span/zero calibration application ----------

In [14]:
calibration = {
    "PM2.5": {"zero": 2, "span": 1.05},
    "SO2": {"zero": 1, "span": 1.02},
    "NOx": {"zero": 1, "span": 1.03}
}

for i in calibration:
    zero = calibration[i]["zero"]
    span = calibration[i]["span"]
    
    demo[i] = (demo[i] - zero) * span

demo.head()

,Record_ID,Plant_ID,TS,PM2.5,SO2,NOx,Unit,Status,Latitude,Longitude
0,E20000,PL-08,2026-01-01 00:00:00,74.655,18.054,25.132,ug/m3,ok,13.2214,81.4807
1,E20001,PL-01,2026-01-01 00:10:00,74.655,25.704,50.367,ug/m3,ok,12.6208,79.5575
2,E20002,PL-10,2026-01-01 00:20:00,85.050,25.602,45.835,ug/m3,maintenance,12.7270,81.2451
3,E20003,PL-17,2026-01-01 00:30:00,65.625,30.600,50.367,ug/m3,maintenance,13.5187,81.0188
4,E20004,PL-11,2026-01-01 00:40:00,84.105,21.420,52.427,ug/m3,ok,13.2038,80.0315

---------- 8. Outlier filtering using rolling median and Hampel filters ----------

In [15]:
def hampel_filter(series, w=5, n=3):
    rolling_median = series.rolling(w).median()
    diff = np.abs(series - rolling_median)
    mad = diff.rolling(w).median()

    threshold = n * mad
    outlier = diff > threshold

    series[outlier] = np.nan
    return series

demo["PM2.5"] = hampel_filter(demo["PM2.5"])
demo["SO2"] = hampel_filter(demo["SO2"])
demo["NOx"] = hampel_filter(demo["NOx"])

demo.head()

,Record_ID,Plant_ID,TS,PM2.5,SO2,NOx,Unit,Status,Latitude,Longitude
0,E20000,PL-08,2026-01-01 00:00:00,74.655,18.054,25.132,ug/m3,ok,13.2214,81.4807
1,E20001,PL-01,2026-01-01 00:10:00,74.655,25.704,50.367,ug/m3,ok,12.6208,79.5575
2,E20002,PL-10,2026-01-01 00:20:00,85.050,25.602,45.835,ug/m3,maintenance,12.7270,81.2451
3,E20003,PL-17,2026-01-01 00:30:00,65.625,30.600,50.367,ug/m3,maintenance,13.5187,81.0188
4,E20004,PL-11,2026-01-01 00:40:00,84.105,21.420,52.427,ug/m3,ok,13.2038,80.0315

---------- 9. Missing gap filling within allowed substitution rules ----------

In [16]:
pollutants = ["PM2.5", "SO2", "NOx"]

demo[pollutants] = demo[pollutants].interpolate(limit=2)
demo[pollutants].isna().sum()

demo.head()

,Record_ID,Plant_ID,TS,PM2.5,SO2,NOx,Unit,Status,Latitude,Longitude
0,E20000,PL-08,2026-01-01 00:00:00,74.655,18.054,25.132,ug/m3,ok,13.2214,81.4807
1,E20001,PL-01,2026-01-01 00:10:00,74.655,25.704,50.367,ug/m3,ok,12.6208,79.5575
2,E20002,PL-10,2026-01-01 00:20:00,85.050,25.602,45.835,ug/m3,maintenance,12.7270,81.2451
3,E20003,PL-17,2026-01-01 00:30:00,65.625,30.600,50.367,ug/m3,maintenance,13.5187,81.0188
4,E20004,PL-11,2026-01-01 00:40:00,84.105,21.420,52.427,ug/m3,ok,13.2038,80.0315

---------- 10. Instrument downtime labeling from maintenance logs ----------

In [17]:
demo["Downtime"] = demo["Status"].isin(["maintenance"])
demo[["Status", "Downtime"]].head()

        Status  Downtime
0           ok     False
1           ok     False
2  maintenance      True
3  maintenance      True
4           ok     False

---------- 11. Limit of detection (LOD) handling (below LOD → half LOD) ----------

In [19]:
LOD = {"PM2.5": 5, "SO2": 3, "NOx": 4}

for col in pollutants:
    df.loc[df[col] < LOD[col], col] = LOD[col] / 2

df[pollutants].describe()

             PM2.5          SO2          NOx
count  6500.000000  6500.000000  6500.000000
mean     68.815031    25.969251    52.454765
std      44.296925    13.554530    46.844441
min       2.500000     1.500000     2.000000
25%      39.690000    18.870000    30.906000
50%      68.012000    25.500000    50.399000
75%      97.020000    32.295750    69.993000
max    1937.950000   452.778000  1826.282000

In [20]:
# 12. STATUS NORMALIZATION

df["Status"] = df["Status"].replace({
    "MAINTENANCE": "MAINT",
    "MAINT ": "MAINT",
    "MAINTENANCE ": "MAINT",
    "OK ": "OK",
    "FAULTY": "FAULT",
    "ERROR": "FAULT"
})

df["Status"].unique()

<StringArray>
['MAINT', 'OK', 'FAULT', 'UNKNOWN', '?', 'ERR', '--', '0', nan]
Length: 9, dtype: str

In [21]:
# 13. STACK TO PLANT MAPPING VALIDATION

# Dummy master mapping table (since Stack_ID not present in raw dataset)
plant_stack_map = {
    "PL-01": "ST-01",
    "PL-02": "ST-02",
    "PL-03": "ST-03",
    "PL-04": "ST-04",
    "PL-05": "ST-05",
    "PL-06": "ST-06",
    "PL-07": "ST-07",
    "PL-08": "ST-08",
    "PL-09": "ST-09"
}

# Create Stack_ID from Plant_ID
df["Stack_ID"] = df["Plant_ID"].map(plant_stack_map)

# Validation flag (1 = invalid mapping, 0 = valid)
df["Stack_Map_Flag"] = df["Stack_ID"].isna().astype(int)

# Optional: Keep only valid rows (comment this if you want audit trace)
# df = df[df["Stack_Map_Flag"] == 0]

# Verification
df[["Plant_ID", "Stack_ID", "Stack_Map_Flag"]].head()

  Plant_ID Stack_ID  Stack_Map_Flag
0    PL-01    ST-01               0
1    PL-01    ST-01               0
2    PL-01    ST-01               0
3    PL-01    ST-01               0
4    PL-01    ST-01               0

In [22]:
# 14. UNIT CONVERSION

df.loc[df["Unit"] == "mg/nm3", pollutants] *= 1000
df["Unit"] = "ug/m3"

df["Unit"].unique()

<StringArray>
['ug/m3']
Length: 1, dtype: str

In [23]:
# 15. SOURCE TAGGING

df["Source"] = "STACK"

df["Source"].head()

0    STACK
1    STACK
2    STACK
3    STACK
4    STACK
Name: Source, dtype: str

In [24]:
# 16. QC FLAG

df["QC_Flag"] = np.where(df[pollutants].isna().any(axis=1), 1, 0)

df["QC_Flag"].value_counts()

QC_Flag
0    6500
Name: count, dtype: int64

In [25]:
# 17. CONVERSION TO IST

df["TS"] = pd.to_datetime(df["TS"], errors="coerce")

if df["TS"].dt.tz is None:
    df["TS"] = df["TS"].dt.tz_localize("Asia/Kolkata")
else:
    df["TS"] = df["TS"].dt.tz_convert("Asia/Kolkata")

df["TS"].head()

0   2026-01-02 23:00:00+05:30
1                         NaT
2                         NaT
3                         NaT
4   2026-05-02 22:10:00+05:30
Name: TS, dtype: datetime64[us, Asia/Kolkata]

In [26]:
# 18. PII REMOVAL

df["Inspection_Notes"] = "REDACTED"

In [27]:
# 19. THRESHOLD JOIN

threshold = 60
df["PM25_Exceed"] = np.where(df["PM2.5"] > threshold, 1, 0)

df["PM25_Exceed"].value_counts()

PM25_Exceed
1    4646
0    1854
Name: count, dtype: int64

In [28]:
# 20. AUDIT TRAIL

df["Audit"] = "Cleaned_v1"

In [2]:
# FINAL RENAME + SAVE + New File

df = df.rename(columns={
    "PM2.5": "PM2_5_ugm3",
    "SO2": "SO2_ugm3",
    "NOx": "NOx_ugm3"
})

df.to_csv("cleaned_pollution.csv", index=False)
df

,Record_ID,Plant_ID,Stack_ID,TS,PM2_5_ugm3,SO2_ugm3,NOx_ugm3,Unit,Latitude,Longitude,...,Calibration_Offset,Span_Factor,Lab_Entry_1,Lab_Entry_2,Maintenance_Flag,Inspection_Notes,PM25_Limit,SO2_Limit,NOx_Limit,Correction_Log
0,E20000,PL-08,STK-008-A,2026-01-01 00:00+05:30,73.1,18.7,25.4,ug/m³,13.2214,81.4807,...,0.0,1.0,73.1,73.1,NaN,NaN,NaN,NaN,NaN,NaN
1,E20001,PL-01,STK-001-A,2026-01-01 00:10,73.1,26.2,49.9,ug/m3,12.6208,79.5575,...,0.0,1.0,73.1,73.1,NaN,NaN,NaN,NaN,NaN,NaN
2,E20002,PL-10,STK-010-A,2026-01-01 00:20,83.0,26.1,45.5,UG/m3,12.7270,81.2451,...,0.0,1.0,83.0,83.0,NaN,NaN,NaN,NaN,NaN,NaN
3,E20003,PL-17,STK-017-A,2026-01-01 00:30,64.5,31.0,49.9,ug/m3,13.5187,81.0188,...,0.0,1.0,64.5,64.5,NaN,NaN,NaN,NaN,NaN,NaN
4,E20004,PL-11,STK-011-A,2026-01-01 00:40,82.1,22.0,51.9,µg/m³,13.2038,80.0315,...,0.0,1.0,82.1,82.1,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6625,E22690,PL-01,STK-001-A,2026-01-19 16:20,5.7,22.8,24.7,mg/nm3,12.6203,79.9658,...,0.0,1.0,5.7,5.7,NaN,NaN,NaN,NaN,NaN,NaN
6626,E26085,PL-14,STK-014-A,2026-02-12 06:10,129.6,35.8,80.4,UG/m3,13.4076,80.4396,...,0.0,1.0,125.6,125.6,NaN,NaN,NaN,NaN,NaN,NaN
6627,E20397,PL-02,STK-002-A,2026-01-03 18:10,11.0,NaN,11.0,UG/m3,13.6809,79.5160,...,0.0,1.0,10.6,10.6,NaN,NaN,NaN,NaN,NaN,NaN
6628,E24722,PL-02,STK-002-A,2026-02-02 19:00,17.1,9.0,24.2,mg/Nm3,14.4605,80.7726,...,0.0,1.0,18.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN
6629,E21263,PL-20,STK-020-A,2026-01-09 18:30,27.4,NaN,31.5,mg/nm3,13.7189,81.1412,...,0.0,1.0,27.4,27.4,NaN,SO2:<0.5,NaN,NaN,NaN,NaN